export default [
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: {
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        location: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        fetch: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        Event: "readonly",
        CustomEvent: "readonly",
        Promise: "readonly",
        alert: "readonly",
        confirm: "readonly",
        prompt: "readonly",
        Blob: "readonly",
        FileReader: "readonly",
        Audio: "readonly",
        Image: "readonly",
        HTMLElement: "readonly",
        Node: "readonly",
        FormData: "readonly",
        crypto: "readonly",
        atob: "readonly",
        btoa: "readonly",
        structuredClone: "readonly",
        self: "readonly",
        caches: "readonly",
        indexedDB: "readonly",
        performance: "readonly",
        MissionControl: "readonly",
        Assistant: "readonly",
        supabase: "readonly",
        supabaseClient: "readonly",
        SUPABASE_URL: "readonly",
        SUPABASE_ANON_KEY: "readonly",
      },
    },
    rules: {
      "no-undef": "error",
      "no-const-assign": "error",
      "no-dupe-keys": "error",
      "no-dupe-args": "error",
      "no-duplicate-case": "error",
      "no-unreachable": "warn",
      "no-cond-assign": "error",
      "no-func-assign": "error",
      "no-invalid-regexp": "error",
      "no-obj-calls": "error",
      "use-isnan": "error",
      "valid-typeof": "error",
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
    },
  },
  {
    ignores: ["**/node_modules/**", "**/.git/**", "**/supabase/functions/**", "eslint.config.mjs"],
  },
];
